services:
  - name: backup-db
    type: cron
    schedule: "0 3 * * *"
    region: oregon
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: replace-with-your-postgres-instance-name
          property: connectionString
      # pick the region closest to your database
      # For example, us-west-2 for the Oregon region
      - key: AWS_REGION
        sync: false 
      # A globally unique name for your bucket
      # For example, <your-username>-<database name>-render-postgres-backups
      - key: S3_BUCKET_NAME
        sync: false
      # Looks like "AKIAXXXXXXXXXXXXXXXX"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      # Postgres version of your Postgres instance 
      # For example, 16
      - key: POSTGRES_VERSION
        sync: false
      # Alpine base-OS version, see README
      # For example, 3.20
      - key: ALPINE_VERSION
        sync: false

