services:
  - name: backup-db
    type: cron
    schedule: "0 4 * * *"
    region: ohio
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: postgresql://db_dvg6_user:hLxqMOMX1yQ9HmNndeM7UDimCGaEmG8X@dpg-cdl4clkgqg43pc58b18g-a/db_dvg6
        fromDatabase:
          name: db
          property: connectionString
      # pick the region closest to your database
      # For example, us-west-2 for the Oregon region
      - key: AWS_REGION
        sync: false 
      # A globally unique name for your bucket
      # For example, <your-username>-<database name>-render-postgres-backups
      - key: S3_BUCKET_NAME
        sync: false
      # Looks like "AKIAXXXXXXXXXXXXXXXX"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      # Postgres version of your Postgres instance 
      # For example, 16
      - key: POSTGRES_VERSION
        sync: false
      # Alpine base-OS version, see README
      # For example, 3.20
      - key: ALPINE_VERSION
        sync: false

