services:
  - name: backup-db
    type: cron
    schedule: "0 3 * * *"
    region: oregon
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: platform-db-application-prod
          property: connectionString
      - key: AWS_REGION
        value: "us-west-2"
        sync: false
      - key: S3_BUCKET_NAME
        value: instil-render-prod-database-backups
        sync: false
      - key: AWS_ACCESS_KEY_ID
        value: ${{ secrets.AWS_ACCESS_KEY_ID }}
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        sync: false
      - key: POSTGRES_VERSION
        value: 16
        sync: false
      - key: ALPINE_VERSION
        value: 3.20
        sync: false

